import type { Service, Project, BlogPost, Testimonial, TeamMember, FAQ } from "@/types";

export const SERVICES: Service[] = [
  {
    id: "mobile-app",
    icon: "Smartphone",
    title: "Mobile App Development",
    description: "Custom Android and iOS mobile applications tailored to your business needs with seamless user experiences.",
    features: ["Android Development", "iOS Development", "Cross-Platform Apps", "Push Notifications", "API Integration", "Location Services"],
    technologies: ["React Native", "Flutter", "Firebase", "REST APIs"],
    color: "#00b4ff",
  },
  {
    id: "website-dev",
    icon: "Globe",
    title: "Website Development",
    description: "Professional, responsive websites that establish your brand presence and drive business growth.",
    features: ["Landing Pages", "Corporate Websites", "E-commerce", "CMS Integration", "SEO-Ready", "Performance Optimized"],
    technologies: ["React", "Next.js", "WordPress", "Tailwind CSS"],
    color: "#00e5ff",
  },
  {
    id: "web-app",
    icon: "Layout",
    title: "Web Application Development",
    description: "Scalable, feature-rich web applications that power your business operations and delight users.",
    features: ["SaaS Platforms", "Admin Dashboards", "Real-time Features", "Authentication", "Database Design", "Cloud Deployment"],
    technologies: ["React", "Node.js", "MongoDB", "PostgreSQL"],
    color: "#7c3aed",
  },
  {
    id: "ui-ux",
    icon: "Palette",
    title: "UI/UX Design",
    description: "User-centered design that balances aesthetics with functionality to create memorable digital experiences.",
    features: ["Wireframing", "Prototyping", "User Research", "Design Systems", "Responsive Design", "Interaction Design"],
    technologies: ["Figma", "Adobe XD", "Framer", "Protopie"],
    color: "#f59e0b",
  },
  {
    id: "custom-software",
    icon: "Code2",
    title: "Custom Software Development",
    description: "Bespoke software solutions engineered to solve your unique business challenges and automate processes.",
    features: ["Business Automation", "ERP/CRM Systems", "Inventory Management", "Reporting Tools", "Integrations", "Legacy Modernization"],
    technologies: ["Node.js", "Python", "React", "PostgreSQL"],
    color: "#10b981",
  },
  {
    id: "api-backend",
    icon: "Server",
    title: "API & Backend Development",
    description: "Robust, secure, and scalable backend architectures and API services for your digital products.",
    features: ["RESTful APIs", "GraphQL", "Microservices", "Authentication Systems", "Database Optimization", "Cloud Infrastructure"],
    technologies: ["Node.js", "Express", "MongoDB", "AWS"],
    color: "#ef4444",
  },
  {
    id: "maintenance",
    icon: "Wrench",
    title: "Maintenance & Support",
    description: "Ongoing technical support and maintenance to keep your digital products running at peak performance.",
    features: ["Bug Fixes", "Performance Tuning", "Security Updates", "Feature Additions", "Monitoring", "24/7 Support"],
    technologies: ["All Stacks", "CI/CD", "Docker", "Cloud Tools"],
    color: "#06b6d4",
  },
  {
    id: "seo",
    icon: "TrendingUp",
    title: "SEO & Digital Presence",
    description: "Improve your search engine rankings and establish a strong online presence to attract more clients.",
    features: ["Technical SEO", "On-Page SEO", "Performance Optimization", "Core Web Vitals", "Analytics Setup", "Content Strategy"],
    technologies: ["Google Analytics", "Search Console", "Lighthouse", "Schema.org"],
    color: "#8b5cf6",
  },
];

export const PROJECTS: Project[] = [
  {
    id: "1",
    title: "ShopEase — E-Commerce Platform",
    category: "Web Application",
    description: "A full-featured e-commerce web application with product catalog, cart, payments, and admin panel for a retail chain.",
    problem: "The client needed a scalable e-commerce solution to replace their manual ordering system.",
    solution: "Built a complete e-commerce platform with real-time inventory and integrated payment gateway.",
    technologies: ["React", "Node.js", "MongoDB", "Stripe", "Tailwind CSS"],
    features: ["Product Catalog", "Shopping Cart", "Payment Gateway", "Order Tracking", "Admin Dashboard"],
    image: "https://images.unsplash.com/photo-1661956602944-249bcd04b63f?w=800&h=500&fit=crop&q=80",
    status: "Live",
    liveUrl: "https://shopease.demo",
    featured: true,
  },
  {
    id: "2",
    title: "MediCare — Healthcare Mobile App",
    category: "Mobile App",
    description: "A cross-platform healthcare app enabling patients to book appointments, consult doctors, and manage prescriptions.",
    problem: "Patients had difficulty accessing medical consultations and managing health records remotely.",
    solution: "Developed a comprehensive healthcare app with telemedicine features and secure health record management.",
    technologies: ["React Native", "Firebase", "Node.js", "MongoDB"],
    features: ["Doctor Booking", "Video Consultation", "Prescription Management", "Health Records", "Reminders"],
    image: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800&h=500&fit=crop&q=80",
    status: "Live",
    featured: true,
  },
  {
    id: "3",
    title: "TaskFlow — Project Management SaaS",
    category: "Web Application",
    description: "A modern project management SaaS for small teams with kanban boards, time tracking, and team collaboration.",
    technologies: ["React", "Node.js", "PostgreSQL", "Socket.io"],
    features: ["Kanban Boards", "Time Tracking", "Team Chat", "File Sharing", "Progress Analytics"],
    image: "https://images.unsplash.com/photo-1611224923853-80b023f02d71?w=800&h=500&fit=crop&q=80",
    status: "Completed",
    featured: true,
  },
  {
    id: "4",
    title: "GreenLeaf — Organic Store Website",
    category: "Website",
    description: "A visually rich website for an organic food brand with product showcase, blog, and online enquiry system.",
    technologies: ["React", "WordPress CMS", "Tailwind CSS", "MySQL"],
    features: ["Product Showcase", "Blog Section", "Enquiry Form", "SEO Optimized", "Responsive Design"],
    image: "https://images.unsplash.com/photo-1542838132-92c53300491e?w=800&h=500&fit=crop&q=80",
    status: "Live",
    liveUrl: "https://greenleaf.demo",
  },
  {
    id: "5",
    title: "LogiTrack — Logistics Dashboard",
    category: "Web Application",
    description: "A real-time logistics tracking dashboard for a supply chain company managing 500+ daily deliveries.",
    technologies: ["React", "Node.js", "MongoDB", "Google Maps API", "Socket.io"],
    features: ["Real-Time Tracking", "Route Optimization", "Driver Management", "Analytics Dashboard", "Client Portal"],
    image: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&h=500&fit=crop&q=80",
    status: "In Progress",
  },
  {
    id: "6",
    title: "EduSpark — Learning Platform",
    category: "Mobile App",
    description: "An educational mobile application for K-12 students with interactive lessons, quizzes, and progress tracking.",
    technologies: ["React Native", "Firebase", "Node.js", "AWS S3"],
    features: ["Interactive Lessons", "Quizzes & Tests", "Progress Tracking", "Parent Dashboard", "Offline Mode"],
    image: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800&h=500&fit=crop&q=80",
    status: "Completed",
  },
];

export const BLOG_POSTS: BlogPost[] = [
  {
    id: "1",
    title: "How React Native Is Revolutionizing Cross-Platform Mobile Development in 2026",
    slug: "react-native-cross-platform-2026",
    excerpt: "Discover how React Native continues to dominate the cross-platform mobile development landscape and why startups should consider it for their next project.",
    author: "Arjun Mehta",
    date: "Aug 28, 2026",
    category: "Mobile Development",
    tags: ["React Native", "Mobile App", "Cross-Platform", "Startups"],
    image: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=800&h=450&fit=crop&q=80",
    readTime: "6 min read",
  },
  {
    id: "2",
    title: "Building Scalable Web Applications: A Complete Architecture Guide",
    slug: "scalable-web-app-architecture",
    excerpt: "Learn the key architectural patterns and best practices for building web applications that can scale from 100 to 1 million users without a complete rewrite.",
    author: "Priya Sharma",
    date: "Aug 20, 2026",
    category: "Web Development",
    tags: ["Architecture", "Node.js", "Scalability", "Best Practices"],
    image: "https://images.unsplash.com/photo-1667372393119-3d4c48d07fc9?w=800&h=450&fit=crop&q=80",
    readTime: "8 min read",
  },
  {
    id: "3",
    title: "Why Every Indian Startup Needs a Mobile App in 2026",
    slug: "indian-startups-mobile-app-2026",
    excerpt: "With over 1.2 billion smartphone users in India, discover why having a mobile app is no longer optional for startups looking to scale their business.",
    author: "Rahul Verma",
    date: "Aug 14, 2026",
    category: "Startup",
    tags: ["Startups", "India", "Mobile App", "Business Strategy"],
    image: "https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=800&h=450&fit=crop&q=80",
    readTime: "5 min read",
  },
  {
    id: "4",
    title: "UI/UX Design Trends That Will Define Digital Products in 2027",
    slug: "ui-ux-design-trends-2027",
    excerpt: "From neomorphism to AI-generated interfaces, explore the cutting-edge design trends that are shaping user experiences across web and mobile platforms.",
    author: "Sneha Patel",
    date: "Aug 6, 2026",
    category: "UI/UX Design",
    tags: ["UI Design", "UX Design", "Design Trends", "Product Design"],
    image: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800&h=450&fit=crop&q=80",
    readTime: "7 min read",
  },
  {
    id: "5",
    title: "The Complete Guide to SEO for Technology Companies",
    slug: "seo-guide-technology-companies",
    excerpt: "A detailed walkthrough of SEO strategies specifically designed for software companies, IT services, and technology startups targeting Indian and global markets.",
    author: "Arjun Mehta",
    date: "Jul 29, 2026",
    category: "SEO & Marketing",
    tags: ["SEO", "Digital Marketing", "Technology", "Lead Generation"],
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&h=450&fit=crop&q=80",
    readTime: "10 min read",
  },
  {
    id: "6",
    title: "Choosing Between PostgreSQL and MongoDB for Your Next Project",
    slug: "postgresql-vs-mongodb-comparison",
    excerpt: "An in-depth comparison of two leading database technologies — when to use each, their trade-offs, and real-world use cases from our development experience.",
    author: "Rahul Verma",
    date: "Jul 21, 2026",
    category: "Backend Development",
    tags: ["PostgreSQL", "MongoDB", "Database", "Backend"],
    image: "https://images.unsplash.com/photo-1544383835-bda2bc66a55d?w=800&h=450&fit=crop&q=80",
    readTime: "9 min read",
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: "1",
    name: "Vikram Nair",
    company: "RetailX India",
    role: "Founder & CEO",
    review: "MassX delivered our e-commerce platform on time and exceeded expectations. The team's technical expertise and attention to detail is outstanding. Our sales have grown 3x since launch.",
    rating: 5,
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=80&h=80&fit=crop&q=80",
  },
  {
    id: "2",
    name: "Dr. Ananya Singh",
    company: "MediConnect Clinics",
    role: "Co-Founder",
    review: "The healthcare app MassX built for us has transformed how our patients interact with our services. Excellent design, smooth performance, and great post-launch support.",
    rating: 5,
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=80&h=80&fit=crop&q=80",
  },
  {
    id: "3",
    name: "Rohan Kapoor",
    company: "Kapoor Enterprises",
    role: "Managing Director",
    review: "We needed a complete business management system and MassX delivered a solution that perfectly fits our workflow. Professional team, transparent communication throughout.",
    rating: 5,
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=80&h=80&fit=crop&q=80",
  },
  {
    id: "4",
    name: "Preethi Kumar",
    company: "EduSphere Learning",
    role: "Product Head",
    review: "Our learning app required complex features and MassX handled it brilliantly. The React Native app performs flawlessly on both Android and iOS. Highly recommended!",
    rating: 5,
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=80&h=80&fit=crop&q=80",
  },
  {
    id: "5",
    name: "Ajay Deshmukh",
    company: "LogiChain Solutions",
    role: "CTO",
    review: "The real-time logistics dashboard MassX built reduced our delivery errors by 40%. Their technical knowledge and problem-solving approach is top-notch.",
    rating: 5,
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=80&h=80&fit=crop&q=80",
  },
];

export const TEAM_MEMBERS: TeamMember[] = [
  {
    id: "1",
    name: "Arjun Mehta",
    role: "Founder & CEO",
    bio: "Full-stack developer with 8+ years of experience. Passionate about building technology solutions that create real business impact.",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop&q=80",
    linkedin: "#",
    github: "#",
  },
  {
    id: "2",
    name: "Priya Sharma",
    role: "Lead Frontend Developer",
    bio: "React specialist with expertise in crafting pixel-perfect, performant web and mobile interfaces.",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop&q=80",
    linkedin: "#",
    github: "#",
  },
  {
    id: "3",
    name: "Rahul Verma",
    role: "Backend Engineer",
    bio: "Node.js and cloud infrastructure expert focused on building scalable, secure APIs and microservices.",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop&q=80",
    linkedin: "#",
    github: "#",
  },
  {
    id: "4",
    name: "Sneha Patel",
    role: "UI/UX Designer",
    bio: "Creative designer with a strong foundation in user research, interaction design, and visual systems.",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop&q=80",
    linkedin: "#",
  },
];

export const TECH_STACK = [
  { name: "React", logo: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg", category: "Frontend" },
  { name: "React Native", logo: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg", category: "Mobile" },
  { name: "Node.js", logo: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nodejs/nodejs-original.svg", category: "Backend" },
  { name: "TypeScript", logo: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-original.svg", category: "Language" },
  { name: "JavaScript", logo: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg", category: "Language" },
  { name: "MongoDB", logo: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mongodb/mongodb-original.svg", category: "Database" },
  { name: "PostgreSQL", logo: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/postgresql/postgresql-original.svg", category: "Database" },
  { name: "MySQL", logo: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mysql/mysql-original.svg", category: "Database" },
  { name: "Firebase", logo: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/firebase/firebase-plain.svg", category: "Cloud" },
  { name: "AWS", logo: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/amazonwebservices/amazonwebservices-plain-wordmark.svg", category: "Cloud" },
  { name: "Docker", logo: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/docker/docker-original.svg", category: "DevOps" },
  { name: "Git", logo: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/git/git-original.svg", category: "DevOps" },
  { name: "Flutter", logo: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/flutter/flutter-original.svg", category: "Mobile" },
  { name: "Figma", logo: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/figma/figma-original.svg", category: "Design" },
  { name: "HTML5", logo: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-original.svg", category: "Frontend" },
  { name: "CSS3", logo: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/css3/css3-original.svg", category: "Frontend" },
];

export const FAQS: FAQ[] = [
  {
    id: "1",
    question: "How long does it take to develop a mobile app?",
    answer: "Development time depends on complexity. A basic app typically takes 4–8 weeks, a medium-complexity app 8–16 weeks, and feature-rich enterprise apps can take 4–6 months. We provide a detailed timeline after the initial discovery call.",
    category: "Development",
  },
  {
    id: "2",
    question: "Do you develop apps for both Android and iOS?",
    answer: "Yes! We develop native Android apps, native iOS apps, and cross-platform apps using React Native or Flutter — which allows a single codebase to run on both platforms, reducing costs significantly.",
    category: "Mobile Development",
  },
  {
    id: "3",
    question: "What is your development process?",
    answer: "We follow an agile development methodology: Discovery → Planning → UI/UX Design → Development → Testing & QA → Deployment → Post-launch Support. You receive regular updates and demos at every milestone.",
    category: "Process",
  },
  {
    id: "4",
    question: "What are your pricing models?",
    answer: "We offer Fixed-Price projects for well-defined scopes, Time & Material for evolving requirements, and Monthly Retainer for ongoing development. We tailor pricing to your budget and project needs.",
    category: "Pricing",
  },
  {
    id: "5",
    question: "Do you provide post-launch support?",
    answer: "Absolutely. All projects include a free 30-day post-launch support period. We also offer ongoing maintenance packages to handle updates, bug fixes, performance optimization, and feature additions.",
    category: "Support",
  },
  {
    id: "6",
    question: "Will I own the source code after project completion?",
    answer: "Yes. Upon final payment, full ownership of source code and all project assets is transferred to you. You have 100% rights to the product we build for you.",
    category: "Legal",
  },
  {
    id: "7",
    question: "Can you redesign or rebuild my existing website/app?",
    answer: "Yes! We specialize in redesigns and rebuilds. We analyze your current product, identify areas for improvement, and deliver a modern, optimized version while preserving your existing data and business logic.",
    category: "Services",
  },
  {
    id: "8",
    question: "How do you handle project communication?",
    answer: "We use WhatsApp, email, and video calls for regular communication. You get a dedicated project manager who provides weekly progress reports and is available for any questions throughout development.",
    category: "Process",
  },
];

export const WORK_PROCESS = [
  { step: "01", title: "Requirement Analysis", description: "We deeply understand your business goals, target users, and technical requirements.", icon: "FileSearch" },
  { step: "02", title: "Planning & Strategy", description: "Detailed project roadmap, technology selection, and resource planning.", icon: "Map" },
  { step: "03", title: "UI/UX Design", description: "Wireframes, prototypes, and visual designs that prioritize user experience.", icon: "Palette" },
  { step: "04", title: "Development", description: "Agile development with regular demos and transparent progress updates.", icon: "Code2" },
  { step: "05", title: "Testing & QA", description: "Rigorous testing across devices, browsers, and edge cases.", icon: "CheckCircle" },
  { step: "06", title: "Deployment", description: "Smooth deployment to production with zero downtime strategy.", icon: "Rocket" },
  { step: "07", title: "Support & Growth", description: "Ongoing maintenance, performance monitoring, and feature expansion.", icon: "HeartHandshake" },
];

export const WHY_CHOOSE_US = [
  { icon: "Zap", title: "Modern Technology Stack", description: "We use the latest, production-proven technologies to build scalable and future-ready solutions." },
  { icon: "Target", title: "Custom Solutions", description: "No templates. Every product is built from scratch to match your exact requirements and vision." },
  { icon: "TrendingUp", title: "Scalable Architecture", description: "Our solutions are designed to grow with your business from Day 1 to 1 million users." },
  { icon: "Users", title: "Client-First Approach", description: "Your success is our priority. We maintain transparent communication throughout every project." },
  { icon: "Shield", title: "Quality Assured", description: "Rigorous testing and code review processes ensure every release meets high quality standards." },
  { icon: "IndianRupee", title: "Affordable & Flexible", description: "Competitive pricing with flexible engagement models designed for Indian startups and businesses." },
];

export const STATS = [
  { value: "50+", label: "Projects Delivered" },
  { value: "40+", label: "Happy Clients" },
  { value: "5+", label: "Years Experience" },
  { value: "15+", label: "Technologies" },
];

export const CONTACT_INFO = {
  phone: "+91 98765 43210",
  email: "hello@massx.in",
  whatsapp: "+919876543210",
  address: "Mumbai, Maharashtra, India",
  social: {
    linkedin: "https://linkedin.com/company/massx",
    instagram: "https://instagram.com/massx",
    facebook: "https://facebook.com/massx",
    twitter: "https://twitter.com/massx",
    youtube: "https://youtube.com/@massx",
    github: "https://github.com/massx",
  },
};
